### ISSUE TITLE
Defining streams as command arguments doesn't work

### ISSUE THREAD

**Issue by sturd** [johnstcn/docker-mpdsnap#1]
SnapServer must have got rid of the `-s` command line argument in the last few months as it was not obeying that for me when I've attempted to use this project.

Just leaving this here for your future reference.  [This commit](https://gitlab.com/sturd/docker-snapcast/commit/5b51a1175126c687de18d2295c3cb8fe43a61341) details the change to fix.

**Comment by johnstcn** [comment]
Thanks @sturd! Pushed a fix and verified locally it works for me.
